@echo off
echo Clearing the Terminal...
cls
echo Running RISC-V assembler...
py risc_v.py
echo Compiling Verilog testbench...
iverilog wrapper.v
echo Running simulation...
vvp a.out
echo Converting to Decimals...
py hextodec.py
echo Done!